export const GENRES = [
  "Автобиография",
  "Авторская проза",
  "Ангелы",
  "Боевая фантастика",
  "Боевик",
  "Вампиры",
  "Вестерн",
  "Военная проза",
  "Волшебство",
  "Детектив",
  "Детская литература",
  "Драма",
  "Историческая проза",
  "Исторический роман",
  "Киберпанк",
  "Классика",
  "Космическая опера",
  "Космическая фантастика",
  "Криминальный триллер",
  "Любовный роман",
  "Мистика",
  "Научная фантастика",
  "Приключения",
  "Психологический триллер",
  "Роман",
  "Сказка",
  "Смерть",
  "Тёмное фэнтези",
  "Триллер",
  "Ужасы",
  "Фантастика",
  "Фэнтези",
  "Юмористическая проза",
  "Юмористическое фэнтези",
  "Abridged",
  "Academy",
  "Action",
  "Adult",
  "Adventure",
  "Allegory",
  "Alternate History",
  "Alternate Universe",
  "Angels",
  "Anime",
  "Anthology",
  "Anti-Hero",
  "Antagonist",
  "Apocalypse",
  "Architecture",
  "Arthouse",
  "Artistic Fiction",
  "Arts",
  "Astral Projection",
  "Asynchronous",
  "Aviation",
  "BDSM",
  "Bad Boys",
  "Barbecue",
  "Beastiality",
  "Beauty",
  "Bedroom Athletes",
  "Biker",
  "Bishounen",
  "Bisexual",
  "Black Comedy",
  "Bleach",
  "Boys Love",
  "Broken",
  "Bullet Train",
  "Bureaucracy",
  "Business",
  "Cafe",
  "Campus",
  "Changeling",
  "Chant",
  "Chaos",
  "Chick Lit",
  "Children",
  "Chosen One",
  "Christian Fiction",
  "Chronicles",
  "Classroom",
  "Coleague",
  "Coming of Age",
  "Comics",
  "Commercial",
  "Confession",
  "Conspiracy",
  "Contemporary",
  "Cooking",
  "Cosmic Horror",
  "Crime",
  "Cult",
  "Cupid",
  "Curse",
  "Cyberpunk",
  "DADDY",
  "Dance",
  "Dating Sim",
  "Death",
  "Debt",
  "Demons",
  "Depression",
  "Detective",
  "Devil",
  "Diary",
  "Disability",
  "Disease",
  "Distant Future",
  "Doctor",
  "Dogs",
  "Dollhouse",
  "Doting",
  "Doting Husband",
  "Doting Wife",
  "Drama",
  "Drugs",
  "Dungeon",
  "Dystopia",
  "Education",
  "Elf",
  "Embarrassing",
  "Empowering",
  "Enemies to Lovers",
  "Engagement",
  "Epistolary",
  "Erotic",
  "Espionage",
  "Established Relationship",
  "Fae",
  "Fairies",
  "Fairytale",
  "Fake Relationship",
  "Family",
  "Famous Male Lead",
  "Famous Female Lead",
  "Farming",
  "Fantasy",
  "Fat to Fit",
  "Fate",
  "Father",
  "Female Dominant",
  "Finance",
  "First Love",
  "Fluff",
  "Food Wars",
  "Forced Proximity",
  "Foxes",
  "Fractured",
  "Friends to Lovers",
  "Funny",
  "Fusion",
  "Future",
  "Geek",
  "Gender Bender",
  "Genie",
  "Ghost",
  "Ghosts",
  "Glamour",
  "Glorious",
  "Goddess",
  "Gods",
  "Going Native",
  "Gore",
  "Gothic",
  "Gourmet",
  "Greed",
  "Grimdark",
  "Gripping",
  "Guro",
  "Hacker",
  "Harem",
  "Healing",
  "Hearts",
  "Heaven",
  "Hell",
  "Heroes",
  "Historical",
  "Historical Fantasy",
  "Horror",
  "Hostile",
  "Hot",
  "Huge",
  "Human Trafficking",
  "Humor",
  "Hunger Games",
  "Hunters",
  "Idol",
  "Indecent",
  "Indie",
  "International",
  "Interstellar",
  "Isekai",
  "Josei",
  "Juvenile",
  "Kendo",
  "Kids",
  "Kings",
  "Kissing",
  "Kunoichi",
  "Loli",
  "London",
  "Lonely",
  "Long Distances",
  "Lord",
  "Love Polygon",
  "Love Triangle",
  "Lovers",
  "M-Preg",
  "Mafia",
  "Magical Realism",
  "Maid",
  "Male Pregnancy",
  "Marriage",
  "Marriage of Convenience",
  "Martial Arts",
  "Master",
  "Mated",
  "Mate",
  "Mature",
  "Mech",
  "Medical",
  "Medieval",
  "Memory",
  "Menage",
  "Mermaid",
  "Metropolis",
  "Military",
  "Millionaire",
  "Monster",
  "Monsters",
  "Mystery",
  "Mythology",
  "Naive",
  "Narcissistic",
  "Navy",
  "Near Future",
  "Nerds",
  "Net",
  "News",
  "Noir",
  "Non-fiction",
  "Novel",
  "Nurse",
  "Office",
  "Older Man Younger Woman",
  "Older Woman Younger Man",
  "Omegaverse",
  "One Night Stand",
  "Opposites Attract",
  "Orphan",
  "OT3",
  "OT4",
  "OT5",
  "OT6",
  "Others",
  "Outcast",
  "Pack",
  "Painful",
  "Palace",
  "Panic",
  "Pantheism",
  "Paranormal",
  "Parenting",
  "Part-time Job",
  "Past",
  "Patriarchy",
  "Peaky",
  "Pets",
  "Phobia",
  "Photography",
  "Piercing",
  "Pirates",
  "Play",
  "POV",
  "Power Couple",
  "Power of Love",
  "Pregnancy",
  "Pretty",
  "Price",
  "Priest",
  "Prince",
  "Princess",
  "Prison",
  "Prodigy",
  "Progressive",
  "Protector",
  "Psychic",
  "Punishment",
  "Puppy",
  "Pure",
  "Quest",
  "Rape",
  "Rarity",
  "Rebellion",
  "Redemption",
  "Refuge",
  "Regret",
  "Reincarnation",
  "Relationship",
  "Religion",
  "Rescue",
  "Revenge",
  "Reverse Harem",
  "Rich",
  "Ritual",
  "Road",
  "Robots",
  "Rogue",
  "Romance",
  "Royal",
  "RPG",
  "Sacrifice",
  "Sadism",
  "Sadness",
  "Salaryman",
  "Sales",
  "Sassy Heroine",
  "Satire",
  "Scandal",
  "School",
  "Sci-fi",
  "Science Fiction",
  "Seinen",
  "Self-harm",
  "Sensual",
  "Series",
  "Sexuality",
  "Shadow",
  "Shifter",
  "Shifters",
  "Shiny",
  "Ship",
  "Short Story",
  "Shoujo",
  "Shounen",
  "Shoujo Ai",
  "Shrine",
  "Shy",
  "Siblings",
  "Sickness",
  "Singer",
  "Single",
  "Sisters",
  "Size",
  "Slave",
  "Slavery",
  "Slow",
  "Smart",
  "Smell",
  "Smoke",
  "Soccer",
  "Social",
  "Society",
  "Soldier",
  "Solo",
  "Soul",
  "Sound",
  "Space",
  "Space Opera",
  "Space Western",
  "Speculative Fiction",
  "Spell",
  "Spice",
  "Spirits",
  "Sports",
  "Spy Thriller",
  "Steampunk",
  "Story",
  "Strong",
  "Strong Female Lead",
  "Subaru",
  "Success",
  "Succubi",
  "Succubus",
  "Suck",
  "Suffer",
  "Suicide",
  "Super",
  "Superhero",
  "Superpower",
  "Supernatural",
  "Support",
  "Supreme",
  "Surprise",
  "Surrender",
  "Survival",
  "Suspend",
  "Suspense",
  "Swear",
  "Sweet",
  "Sword",
  "Sword and Sorcery",
  "Sympathetic Monster",
  "System",
  "Tainted",
  "Talent",
  "Talk",
  "Tank",
  "Taste",
  "Taxi",
  "Teacher",
  "Temptation",
  "Tender",
  "Tension",
  "Terror",
  "Theory",
  "Therapy",
  "Thief",
  "Think",
  "Third",
  "Thorn",
  "Thread",
  "Threat",
  "Threesome",
  "Thrill",
  "Thriller",
  "Through",
  "Thunder",
  "Time Loop",
  "Time Stop",
  "Time Travel",
  "Timeless",
  "Tiny",
  "Titan",
  "Title",
  "Toilet",
  "Token",
  "Tomboy",
  "Tone",
  "Tongue",
  "Tool",
  "Top",
  "Torment",
  "Torture",
  "Total",
  "Tour",
  "Tower",
  "Tragedy",
  "Trail",
  "Train",
  "Trans",
  "Transgender",
  "Trap",
  "Trapped",
  "Trash",
  "Travel",
  "Treasure",
  "Tree",
  "Tribe",
  "Trick",
  "Triumph",
  "Trouble",
  "True",
  "True Love",
  "Trust",
  "Truth",
  "Turn",
  "Tutor",
  "Twist",
  "Tyrant",
  "Uncle",
  "Undead",
  "Underage",
  "Undercover",
  "Unexpected",
  "Unfair",
  "Unfulfilled",
  "Unhappy",
  "Unhealthy",
  "Unique",
  "University",
  "Unlawful",
  "Unnatural",
  "Unrequited Love",
  "Unsolved",
  "Unsteady",
  "Untamed",
  "Unwanted",
  "Upper Class",
  "Urban Fantasy",
  "Urban Fiction",
  "Useless",
  "User",
  "Utopia",
  "Vampire",
  "Vanilla",
  "Vast",
  "Vegan",
  "Vengeance",
  "Venue",
  "Verdict",
  "Version",
  "Victim",
  "Victory",
  "Video",
  "Vigilante",
  "Villian",
  "Villain",
  "Violence",
  "Violent",
  "Virtual Reality",
  "Virus",
  "Vision",
  "Visit",
  "Visitor",
  "Vital",
  "Vitamin",
  "Vivacious",
  "Vivid",
  "Vocaloid",
  "Vogue",
  "Voice",
  "Volatile",
  "Volume",
  "Voodoo",
  "Vortex",
  "Vote",
  "Voyage",
  "Vulgar",
  "Vulnerable",
  "Wait",
  "Wake",
  "Walk",
  "Walking Dead",
  "Wanderlust",
  "War",
  "Wardrobe",
  "Warm",
  "Warrior",
  "Waste",
  "Watch",
  "Water",
  "Wave",
  "Weak",
  "Wealth",
  "Weapon",
  "Weather",
  "Web Novel",
  "Wedding",
  "Weed",
  "Weep",
  "Weight",
  "Weird",
  "Welcome",
  "Well",
  "Western",
  "Whale",
  "Whim",
  "Whip",
  "Whisper",
  "White",
  "Wholesome",
  "Wicked",
  "Wife",
  "Wild",
  "Will",
  "Wind",
  "Wine",
  "Winter",
  "Wire",
  "Wisdom",
  "Wish",
  "Witch",
  "Withdrawal",
  "Witness",
  "Woe",
  "Wolf",
  "Womanizer",
  "Wonder",
  "Womb",
  "Wood",
  "Work",
  "Workplace",
  "World",
  "Worm",
  "Worship",
  "Wrath",
  "Wreck",
  "Wrong",
  "Xianxia",
  "Xuanhuan",
  "Yacht",
  "Yandere",
  "Yearning",
  "Yoga",
  "Young",
  "Young Adult",
  "Youth",
  "Zero",
  "Zombie",
  "Zone",
  "Zoology",
];

export function getGenresByLetter(letter: string): string[] {
  if (letter === "ABC") {
    return GENRES.filter(g => /^[A-Z]/.test(g));
  }
  if (letter === "АБВ") {
    return GENRES.filter(g => /^[А-ЯЁ]/.test(g));
  }
  const upper = letter.toUpperCase();
  return GENRES.filter(g => g.toUpperCase().startsWith(upper));
}

export function searchGenres(query: string): string[] {
  if (!query) return [];
  const q = query.toLowerCase();
  return GENRES.filter(g => g.toLowerCase().includes(q)).slice(0, 50);
}